import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Litus AI - decoding the future</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
      <Script type={"text/javascript"} src={"https://cdn.iubenda.com/iubenda.js"} />
    </>
  );
}
